### ISSUE TITLE
[1.18.2] Ender-argo 

### ISSUE THREAD

**Issue by itsdinkd** [AzureDoom/Totally-Enough-Pain#3]
Getting reports that enderman are auto-argoing players. I currently do not have the config set to endermnan_always_attack: true, it's currently set to false.

I believe this might be a bug. 

this is what people are saying, if it helps.

![image](https://user-images.githubusercontent.com/35115304/173478765-ed5a1673-adcb-4ea2-a812-fa50940e2acb.png)

**Comment by AzureDoom** [comment]
Will check out soon!

**Comment by AzureDoom** [comment]
Was a simple issue with the config, fix sent to your discord.
